-- MySQL Script generated by MySQL Workbench
-- Mon Nov  7 01:37:01 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sabor_e_arte
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sabor_e_arte` ;

-- -----------------------------------------------------
-- Schema sabor_e_arte
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sabor_e_arte` DEFAULT CHARACTER SET utf8 ;
USE `sabor_e_arte` ;

-- -----------------------------------------------------
-- Table `sabor_e_arte``.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sabor_e_arte`.`cliente` ;

CREATE TABLE IF NOT EXISTS `sabor_e_arte`.`cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(200) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `cpf` BIGINT NOT NULL,
  `dt_nasc` DATE NOT NULL,
  `telefone` VARCHAR(20) NOT NULL,
  `senha` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cpf_UNIQUE` ON `sabor_e_arte`.`cliente` (`cpf` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sabor_e_arte`.`cardapio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sabor_e_arte`.`cardapio` ;

CREATE TABLE IF NOT EXISTS `sabor_e_arte`.`cardapio` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `preco` DOUBLE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `numero_UNIQUE` ON `sabor_e_arte`.`cardapio` (`numero` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sabor_e_arte`.`ingredientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sabor_e_arte`.`ingredientes` ;

CREATE TABLE IF NOT EXISTS `sabor_e_arte`.`ingredientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `tipo_ingrediente` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sabor_e_arte`.`entregador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sabor_e_arte`.`entregador` ;

CREATE TABLE IF NOT EXISTS `sabor_e_arte`.`entregador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` BIGINT NOT NULL,
  `nome` VARCHAR(200) NOT NULL,
  `meio_transporte` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `cpf_UNIQUE` ON `sabor_e_arte`.`entregador` (`cpf` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sabor_e_arte`.`pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sabor_e_arte`.`pedido` ;

CREATE TABLE IF NOT EXISTS `sabor_e_arte`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `local_entrega` VARCHAR(200) NOT NULL,
  `unidade` VARCHAR(50) NOT NULL,
  `num_pedido` INT UNSIGNED NOT NULL,
  `mtd_pagamento` VARCHAR(100) NOT NULL,
  `valor_total` DOUBLE NOT NULL,
  `observacao` VARCHAR(200) NOT NULL,
  `cliente_id` INT NOT NULL,
  `entregador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `sabor_e_arte`.`cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_entregador1`
    FOREIGN KEY (`entregador_id`)
    REFERENCES `sabor_e_arte`.`entregador` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_pedido_cliente_idx` ON `sabor_e_arte`.`pedido` (`cliente_id` ASC) VISIBLE;

CREATE INDEX `fk_pedido_entregador1_idx` ON `sabor_e_arte`.`pedido` (`entregador_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sabor_e_arte`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sabor_e_arte`.`compra` ;

CREATE TABLE IF NOT EXISTS `sabor_e_arte`.`compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `valor_uni` DOUBLE NOT NULL,
  `quantidade` INT NOT NULL,
  `cardapio_id` INT NOT NULL,
  `pedido_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_compra_cardapio1`
    FOREIGN KEY (`cardapio_id`)
    REFERENCES `sabor_e_arte`.`cardapio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_pedido1`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `sabor_e_arte`.`pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_compra_cardapio1_idx` ON `sabor_e_arte`.`compra` (`cardapio_id` ASC) VISIBLE;

CREATE INDEX `fk_compra_pedido1_idx` ON `sabor_e_arte`.`compra` (`pedido_id` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sabor_e_arte`.`prato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sabor_e_arte`.`prato` ;

CREATE TABLE IF NOT EXISTS `sabor_e_arte`.`prato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `peso` DOUBLE NOT NULL,
  `alergicos` VARCHAR(500) NULL,
  `ingredientes_id` INT NOT NULL,
  `cardapio_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_prato_ingredientes1`
    FOREIGN KEY (`ingredientes_id`)
    REFERENCES `sabor_e_arte`.`ingredientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prato_cardapio1`
    FOREIGN KEY (`cardapio_id`)
    REFERENCES `sabor_e_arte`.`cardapio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_prato_ingredientes1_idx` ON `sabor_e_arte`.`prato` (`ingredientes_id` ASC) VISIBLE;

CREATE INDEX `fk_prato_cardapio1_idx` ON `sabor_e_arte`.`prato` (`cardapio_id` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
